// GENERATED by scripts/generate_icons.py from the SVG files in icons/svg/.
// Draw the glyph, run `./gradlew generateKvadrantIcons`, commit both. `check` fails if this
// file and the drawings disagree.
package io.github.youndie.kvadrant.icons

import androidx.compose.ui.graphics.vector.ImageVector

/**
 * The application bar's glyphs, drawn for this repository.
 *
 * **Nothing here is Microsoft's.** Segoe MDL2 Assets and Segoe Fluent Icons are proprietary and
 * no open Metro-styled equivalent exists, so every one of these is drawn on the grid the
 * guidelines describe: 26 x 26 inside a 48 dp circle, a stroke of 1.5 and no fill. The circle is
 * the bar's, not the glyph's — `KvadrantAppBarButton` draws it.
 *
 * They are strokes rather than fills, so a caller tints them the way Compose tints any vector:
 * `Icon(KvadrantIcons.Back, null)` takes `LocalContentColor` through a colour filter.
 */
public object KvadrantIcons {
    public val Add: ImageVector =
        buildIcon("Add") {
            strokePath {
                moveTo(13.0f, 4.0f)
                lineTo(13.0f, 22.0f)
            }
            strokePath {
                moveTo(4.0f, 13.0f)
                lineTo(22.0f, 13.0f)
            }
        }

    public val Attach: ImageVector =
        buildIcon("Attach") {
            strokePath {
                moveTo(18.0f, 8.0f)
                lineTo(9.0f, 17.0f)
                curveTo(7.0f, 19.0f, 4.0f, 19.0f, 4.0f, 16.0f)
                curveTo(4.0f, 14.0f, 5.0f, 13.0f, 7.0f, 11.0f)
                lineTo(16.0f, 2.5f)
                curveTo(18.0f, 0.5f, 22.0f, 2.0f, 22.0f, 5.0f)
                curveTo(22.0f, 7.0f, 21.0f, 8.0f, 19.0f, 10.0f)
                lineTo(10.0f, 19.0f)
            }
        }

    public val Back: ImageVector =
        buildIcon("Back") {
            strokePath {
                moveTo(23.0f, 13.0f)
                lineTo(4.0f, 13.0f)
            }
            strokePath {
                moveTo(11.0f, 6.0f)
                lineTo(4.0f, 13.0f)
                lineTo(11.0f, 20.0f)
            }
        }

    public val Calendar: ImageVector =
        buildIcon("Calendar") {
            strokePath {
                moveTo(3.0f, 5.0f)
                lineTo(23.0f, 5.0f)
                lineTo(23.0f, 22.0f)
                lineTo(3.0f, 22.0f)
                close()
            }
            strokePath {
                moveTo(3.0f, 10.0f)
                lineTo(23.0f, 10.0f)
            }
            strokePath {
                moveTo(8.0f, 2.0f)
                lineTo(8.0f, 7.0f)
            }
            strokePath {
                moveTo(18.0f, 2.0f)
                lineTo(18.0f, 7.0f)
            }
        }

    public val Camera: ImageVector =
        buildIcon("Camera") {
            strokePath {
                moveTo(3.0f, 8.0f)
                lineTo(8.0f, 8.0f)
                lineTo(10.0f, 5.0f)
                lineTo(16.0f, 5.0f)
                lineTo(18.0f, 8.0f)
                lineTo(23.0f, 8.0f)
                lineTo(23.0f, 21.0f)
                lineTo(3.0f, 21.0f)
                close()
            }
            strokePath {
                moveTo(13.0f, 9.5f)
                curveTo(15.48535f, 9.5f, 17.5f, 11.51465f, 17.5f, 14.0f)
                curveTo(17.5f, 16.48535f, 15.48535f, 18.5f, 13.0f, 18.5f)
                curveTo(10.51465f, 18.5f, 8.5f, 16.48535f, 8.5f, 14.0f)
                curveTo(8.5f, 11.51465f, 10.51465f, 9.5f, 13.0f, 9.5f)
                close()
            }
        }

    public val Cancel: ImageVector =
        buildIcon("Cancel") {
            strokePath {
                moveTo(5.0f, 5.0f)
                lineTo(21.0f, 21.0f)
            }
            strokePath {
                moveTo(21.0f, 5.0f)
                lineTo(5.0f, 21.0f)
            }
        }

    public val Check: ImageVector =
        buildIcon("Check") {
            strokePath {
                moveTo(4.0f, 14.0f)
                lineTo(10.0f, 20.0f)
                lineTo(22.0f, 6.0f)
            }
        }

    public val Clock: ImageVector =
        buildIcon("Clock") {
            strokePath {
                moveTo(13.0f, 3.0f)
                curveTo(18.523f, 3.0f, 23.0f, 7.477f, 23.0f, 13.0f)
                curveTo(23.0f, 18.523f, 18.523f, 23.0f, 13.0f, 23.0f)
                curveTo(7.477f, 23.0f, 3.0f, 18.523f, 3.0f, 13.0f)
                curveTo(3.0f, 7.477f, 7.477f, 3.0f, 13.0f, 3.0f)
                close()
            }
            strokePath {
                moveTo(13.0f, 6.0f)
                lineTo(13.0f, 13.0f)
                lineTo(18.0f, 16.0f)
            }
        }

    public val Close: ImageVector =
        buildIcon("Close") {
            strokePath {
                moveTo(13.0f, 3.0f)
                curveTo(18.5f, 3.0f, 23.0f, 7.5f, 23.0f, 13.0f)
                curveTo(23.0f, 18.5f, 18.5f, 23.0f, 13.0f, 23.0f)
                curveTo(7.5f, 23.0f, 3.0f, 18.5f, 3.0f, 13.0f)
                curveTo(3.0f, 7.5f, 7.5f, 3.0f, 13.0f, 3.0f)
                close()
            }
            strokePath {
                moveTo(9.0f, 9.0f)
                lineTo(17.0f, 17.0f)
            }
            strokePath {
                moveTo(17.0f, 9.0f)
                lineTo(9.0f, 17.0f)
            }
        }

    public val Copy: ImageVector =
        buildIcon("Copy") {
            strokePath {
                moveTo(4.0f, 3.0f)
                lineTo(16.0f, 3.0f)
                lineTo(16.0f, 17.0f)
                lineTo(4.0f, 17.0f)
                close()
            }
            strokePath {
                moveTo(8.0f, 21.0f)
                lineTo(22.0f, 21.0f)
                lineTo(22.0f, 7.0f)
                lineTo(18.0f, 7.0f)
            }
        }

    public val Delete: ImageVector =
        buildIcon("Delete") {
            strokePath {
                moveTo(4.0f, 7.0f)
                lineTo(22.0f, 7.0f)
            }
            strokePath {
                moveTo(10.0f, 7.0f)
                lineTo(10.0f, 4.0f)
                lineTo(16.0f, 4.0f)
                lineTo(16.0f, 7.0f)
            }
            strokePath {
                moveTo(6.0f, 7.0f)
                lineTo(7.0f, 22.0f)
                lineTo(19.0f, 22.0f)
                lineTo(20.0f, 7.0f)
            }
            strokePath {
                moveTo(11.0f, 11.0f)
                lineTo(11.0f, 18.0f)
            }
            strokePath {
                moveTo(15.0f, 11.0f)
                lineTo(15.0f, 18.0f)
            }
        }

    public val Download: ImageVector =
        buildIcon("Download") {
            strokePath {
                moveTo(13.0f, 3.0f)
                lineTo(13.0f, 16.0f)
            }
            strokePath {
                moveTo(7.0f, 11.0f)
                lineTo(13.0f, 17.0f)
                lineTo(19.0f, 11.0f)
            }
            strokePath {
                moveTo(4.0f, 22.0f)
                lineTo(22.0f, 22.0f)
            }
        }

    public val Edit: ImageVector =
        buildIcon("Edit") {
            strokePath {
                moveTo(4.0f, 22.0f)
                lineTo(4.0f, 17.0f)
                lineTo(17.0f, 4.0f)
                lineTo(22.0f, 9.0f)
                lineTo(9.0f, 22.0f)
                close()
            }
            strokePath {
                moveTo(15.0f, 6.0f)
                lineTo(20.0f, 11.0f)
            }
        }

    public val Favourite: ImageVector =
        buildIcon("Favourite") {
            strokePath {
                moveTo(13.0f, 3.0f)
                lineTo(16.0f, 10.0f)
                lineTo(23.0f, 10.5f)
                lineTo(17.5f, 15.0f)
                lineTo(19.5f, 22.0f)
                lineTo(13.0f, 18.0f)
                lineTo(6.5f, 22.0f)
                lineTo(8.5f, 15.0f)
                lineTo(3.0f, 10.5f)
                lineTo(10.0f, 10.0f)
                close()
            }
        }

    public val Folder: ImageVector =
        buildIcon("Folder") {
            strokePath {
                moveTo(3.0f, 6.0f)
                lineTo(10.0f, 6.0f)
                lineTo(12.0f, 9.0f)
                lineTo(23.0f, 9.0f)
                lineTo(23.0f, 21.0f)
                lineTo(3.0f, 21.0f)
                close()
            }
        }

    public val Info: ImageVector =
        buildIcon("Info") {
            strokePath {
                moveTo(13.0f, 3.0f)
                curveTo(18.523f, 3.0f, 23.0f, 7.477f, 23.0f, 13.0f)
                curveTo(23.0f, 18.523f, 18.523f, 23.0f, 13.0f, 23.0f)
                curveTo(7.477f, 23.0f, 3.0f, 18.523f, 3.0f, 13.0f)
                curveTo(3.0f, 7.477f, 7.477f, 3.0f, 13.0f, 3.0f)
                close()
            }
            strokePath {
                moveTo(13.0f, 12.0f)
                lineTo(13.0f, 19.0f)
            }
            strokePath {
                moveTo(13.0f, 7.1f)
                curveTo(13.49707f, 7.1f, 13.9f, 7.50293f, 13.9f, 8.0f)
                curveTo(13.9f, 8.49707f, 13.49707f, 8.9f, 13.0f, 8.9f)
                curveTo(12.50293f, 8.9f, 12.1f, 8.49707f, 12.1f, 8.0f)
                curveTo(12.1f, 7.50293f, 12.50293f, 7.1f, 13.0f, 7.1f)
                close()
            }
        }

    public val Location: ImageVector =
        buildIcon("Location") {
            strokePath {
                moveTo(13.0f, 2.0f)
                curveTo(17.5f, 2.0f, 21.0f, 5.5f, 21.0f, 10.0f)
                curveTo(21.0f, 15.0f, 13.0f, 24.0f, 13.0f, 24.0f)
                curveTo(13.0f, 24.0f, 5.0f, 15.0f, 5.0f, 10.0f)
                curveTo(5.0f, 5.5f, 8.5f, 2.0f, 13.0f, 2.0f)
                close()
            }
            strokePath {
                moveTo(13.0f, 7.0f)
                curveTo(14.6569f, 7.0f, 16.0f, 8.3431f, 16.0f, 10.0f)
                curveTo(16.0f, 11.6569f, 14.6569f, 13.0f, 13.0f, 13.0f)
                curveTo(11.3431f, 13.0f, 10.0f, 11.6569f, 10.0f, 10.0f)
                curveTo(10.0f, 8.3431f, 11.3431f, 7.0f, 13.0f, 7.0f)
                close()
            }
        }

    public val Lock: ImageVector =
        buildIcon("Lock") {
            strokePath {
                moveTo(5.0f, 11.0f)
                lineTo(21.0f, 11.0f)
                lineTo(21.0f, 22.0f)
                lineTo(5.0f, 22.0f)
                close()
            }
            strokePath {
                moveTo(8.0f, 11.0f)
                lineTo(8.0f, 7.0f)
                curveTo(8.0f, 4.0f, 10.0f, 2.0f, 13.0f, 2.0f)
                curveTo(16.0f, 2.0f, 18.0f, 4.0f, 18.0f, 7.0f)
                lineTo(18.0f, 11.0f)
            }
        }

    public val Mail: ImageVector =
        buildIcon("Mail") {
            strokePath {
                moveTo(3.0f, 7.0f)
                lineTo(23.0f, 7.0f)
                lineTo(23.0f, 19.0f)
                lineTo(3.0f, 19.0f)
                close()
            }
            strokePath {
                moveTo(3.0f, 7.0f)
                lineTo(13.0f, 15.0f)
                lineTo(23.0f, 7.0f)
            }
        }

    public val Menu: ImageVector =
        buildIcon("Menu") {
            strokePath {
                moveTo(4.0f, 7.0f)
                lineTo(22.0f, 7.0f)
            }
            strokePath {
                moveTo(4.0f, 13.0f)
                lineTo(22.0f, 13.0f)
            }
            strokePath {
                moveTo(4.0f, 19.0f)
                lineTo(22.0f, 19.0f)
            }
        }

    public val Minus: ImageVector =
        buildIcon("Minus") {
            strokePath {
                moveTo(4.0f, 13.0f)
                lineTo(22.0f, 13.0f)
            }
        }

    public val More: ImageVector =
        buildIcon("More") {
            strokePath {
                moveTo(6.0f, 11.4f)
                curveTo(6.88368f, 11.4f, 7.6f, 12.11632f, 7.6f, 13.0f)
                curveTo(7.6f, 13.88368f, 6.88368f, 14.6f, 6.0f, 14.6f)
                curveTo(5.11632f, 14.6f, 4.4f, 13.88368f, 4.4f, 13.0f)
                curveTo(4.4f, 12.11632f, 5.11632f, 11.4f, 6.0f, 11.4f)
                close()
            }
            strokePath {
                moveTo(13.0f, 11.4f)
                curveTo(13.88368f, 11.4f, 14.6f, 12.11632f, 14.6f, 13.0f)
                curveTo(14.6f, 13.88368f, 13.88368f, 14.6f, 13.0f, 14.6f)
                curveTo(12.11632f, 14.6f, 11.4f, 13.88368f, 11.4f, 13.0f)
                curveTo(11.4f, 12.11632f, 12.11632f, 11.4f, 13.0f, 11.4f)
                close()
            }
            strokePath {
                moveTo(20.0f, 11.4f)
                curveTo(20.88368f, 11.4f, 21.6f, 12.11632f, 21.6f, 13.0f)
                curveTo(21.6f, 13.88368f, 20.88368f, 14.6f, 20.0f, 14.6f)
                curveTo(19.11632f, 14.6f, 18.4f, 13.88368f, 18.4f, 13.0f)
                curveTo(18.4f, 12.11632f, 19.11632f, 11.4f, 20.0f, 11.4f)
                close()
            }
        }

    public val Next: ImageVector =
        buildIcon("Next") {
            strokePath {
                moveTo(6.0f, 4.0f)
                lineTo(17.0f, 13.0f)
                lineTo(6.0f, 22.0f)
                close()
            }
            strokePath {
                moveTo(20.0f, 4.0f)
                lineTo(20.0f, 22.0f)
            }
        }

    public val Pause: ImageVector =
        buildIcon("Pause") {
            strokePath {
                moveTo(9.0f, 4.0f)
                lineTo(9.0f, 22.0f)
            }
            strokePath {
                moveTo(17.0f, 4.0f)
                lineTo(17.0f, 22.0f)
            }
        }

    public val People: ImageVector =
        buildIcon("People") {
            strokePath {
                moveTo(10.0f, 5.0f)
                curveTo(12.2092f, 5.0f, 14.0f, 6.7908f, 14.0f, 9.0f)
                curveTo(14.0f, 11.2092f, 12.2092f, 13.0f, 10.0f, 13.0f)
                curveTo(7.7908f, 13.0f, 6.0f, 11.2092f, 6.0f, 9.0f)
                curveTo(6.0f, 6.7908f, 7.7908f, 5.0f, 10.0f, 5.0f)
                close()
            }
            strokePath {
                moveTo(2.0f, 22.0f)
                curveTo(2.0f, 17.0f, 5.5f, 14.0f, 10.0f, 14.0f)
                curveTo(14.5f, 14.0f, 18.0f, 17.0f, 18.0f, 22.0f)
            }
            strokePath {
                moveTo(19.0f, 5.8f)
                curveTo(20.76736f, 5.8f, 22.2f, 7.23264f, 22.2f, 9.0f)
                curveTo(22.2f, 10.76736f, 20.76736f, 12.2f, 19.0f, 12.2f)
                curveTo(17.23264f, 12.2f, 15.8f, 10.76736f, 15.8f, 9.0f)
                curveTo(15.8f, 7.23264f, 17.23264f, 5.8f, 19.0f, 5.8f)
                close()
            }
            strokePath {
                moveTo(17.0f, 14.4f)
                curveTo(21.0f, 14.6f, 24.0f, 17.6f, 24.0f, 22.0f)
            }
        }

    public val Phone: ImageVector =
        buildIcon("Phone") {
            strokePath {
                moveTo(6.0f, 3.0f)
                lineTo(10.0f, 3.0f)
                lineTo(12.0f, 8.0f)
                lineTo(9.0f, 10.0f)
                curveTo(10.5f, 14.0f, 12.0f, 15.5f, 16.0f, 17.0f)
                lineTo(18.0f, 14.0f)
                lineTo(23.0f, 16.0f)
                lineTo(23.0f, 20.0f)
                curveTo(23.0f, 22.0f, 21.0f, 23.0f, 19.0f, 22.0f)
                curveTo(11.0f, 20.0f, 6.0f, 15.0f, 4.0f, 7.0f)
                curveTo(3.0f, 5.0f, 4.0f, 3.0f, 6.0f, 3.0f)
                close()
            }
        }

    public val Play: ImageVector =
        buildIcon("Play") {
            strokePath {
                moveTo(8.0f, 4.0f)
                lineTo(21.0f, 13.0f)
                lineTo(8.0f, 22.0f)
                close()
            }
        }

    public val Previous: ImageVector =
        buildIcon("Previous") {
            strokePath {
                moveTo(20.0f, 4.0f)
                lineTo(9.0f, 13.0f)
                lineTo(20.0f, 22.0f)
                close()
            }
            strokePath {
                moveTo(6.0f, 4.0f)
                lineTo(6.0f, 22.0f)
            }
        }

    public val Redo: ImageVector =
        buildIcon("Redo") {
            strokePath {
                moveTo(22.0f, 10.0f)
                lineTo(10.0f, 10.0f)
                curveTo(5.0f, 10.0f, 3.0f, 13.0f, 3.0f, 16.0f)
                curveTo(3.0f, 19.0f, 5.0f, 22.0f, 9.0f, 22.0f)
            }
            strokePath {
                moveTo(17.0f, 5.0f)
                lineTo(22.0f, 10.0f)
                lineTo(17.0f, 15.0f)
            }
        }

    public val Refresh: ImageVector =
        buildIcon("Refresh") {
            strokePath {
                moveTo(22.0f, 13.0f)
                curveTo(22.0f, 18.0f, 18.0f, 22.0f, 13.0f, 22.0f)
                curveTo(8.0f, 22.0f, 4.0f, 18.0f, 4.0f, 13.0f)
                curveTo(4.0f, 8.0f, 8.0f, 4.0f, 13.0f, 4.0f)
                curveTo(16.2f, 4.0f, 19.0f, 5.7f, 20.6f, 8.2f)
            }
            strokePath {
                moveTo(15.0f, 8.0f)
                lineTo(21.0f, 8.0f)
                lineTo(21.0f, 2.0f)
            }
        }

    public val Save: ImageVector =
        buildIcon("Save") {
            strokePath {
                moveTo(4.0f, 4.0f)
                lineTo(18.0f, 4.0f)
                lineTo(22.0f, 8.0f)
                lineTo(22.0f, 22.0f)
                lineTo(4.0f, 22.0f)
                close()
            }
            strokePath {
                moveTo(8.0f, 4.0f)
                lineTo(8.0f, 11.0f)
                lineTo(17.0f, 11.0f)
                lineTo(17.0f, 4.0f)
            }
            strokePath {
                moveTo(8.0f, 22.0f)
                lineTo(8.0f, 15.0f)
                lineTo(18.0f, 15.0f)
                lineTo(18.0f, 22.0f)
            }
        }

    public val Search: ImageVector =
        buildIcon("Search") {
            strokePath {
                moveTo(11.0f, 4.0f)
                curveTo(15.4f, 4.0f, 19.0f, 7.6f, 19.0f, 12.0f)
                curveTo(19.0f, 16.4f, 15.4f, 20.0f, 11.0f, 20.0f)
                curveTo(6.6f, 20.0f, 3.0f, 16.4f, 3.0f, 12.0f)
                curveTo(3.0f, 7.6f, 6.6f, 4.0f, 11.0f, 4.0f)
                close()
            }
            strokePath {
                moveTo(17.0f, 18.0f)
                lineTo(23.0f, 24.0f)
            }
        }

    public val Settings: ImageVector =
        buildIcon("Settings") {
            strokePath {
                moveTo(23.86f, 11.28f)
                lineTo(23.86f, 14.72f)
                lineTo(20.78f, 14.87f)
                lineTo(19.82f, 17.18f)
                lineTo(21.9f, 19.47f)
                lineTo(19.47f, 21.9f)
                lineTo(17.18f, 19.82f)
                lineTo(14.87f, 20.78f)
                lineTo(14.72f, 23.86f)
                lineTo(11.28f, 23.86f)
                lineTo(11.13f, 20.78f)
                lineTo(8.82f, 19.82f)
                lineTo(6.53f, 21.9f)
                lineTo(4.1f, 19.47f)
                lineTo(6.18f, 17.18f)
                lineTo(5.22f, 14.87f)
                lineTo(2.14f, 14.72f)
                lineTo(2.14f, 11.28f)
                lineTo(5.22f, 11.13f)
                lineTo(6.18f, 8.82f)
                lineTo(4.1f, 6.53f)
                lineTo(6.53f, 4.1f)
                lineTo(8.82f, 6.18f)
                lineTo(11.13f, 5.22f)
                lineTo(11.28f, 2.14f)
                lineTo(14.72f, 2.14f)
                lineTo(14.87f, 5.22f)
                lineTo(17.18f, 6.18f)
                lineTo(19.47f, 4.1f)
                lineTo(21.9f, 6.53f)
                lineTo(19.82f, 8.82f)
                lineTo(20.78f, 11.13f)
                close()
            }
            strokePath {
                moveTo(13.0f, 9.0f)
                curveTo(15.2092f, 9.0f, 17.0f, 10.7908f, 17.0f, 13.0f)
                curveTo(17.0f, 15.2092f, 15.2092f, 17.0f, 13.0f, 17.0f)
                curveTo(10.7908f, 17.0f, 9.0f, 15.2092f, 9.0f, 13.0f)
                curveTo(9.0f, 10.7908f, 10.7908f, 9.0f, 13.0f, 9.0f)
                close()
            }
        }

    public val Share: ImageVector =
        buildIcon("Share") {
            strokePath {
                moveTo(4.0f, 22.0f)
                lineTo(4.0f, 10.0f)
                lineTo(22.0f, 10.0f)
                lineTo(22.0f, 22.0f)
                close()
            }
            strokePath {
                moveTo(13.0f, 15.0f)
                lineTo(13.0f, 3.0f)
            }
            strokePath {
                moveTo(8.0f, 8.0f)
                lineTo(13.0f, 3.0f)
                lineTo(18.0f, 8.0f)
            }
        }

    public val Stop: ImageVector =
        buildIcon("Stop") {
            strokePath {
                moveTo(6.0f, 6.0f)
                lineTo(20.0f, 6.0f)
                lineTo(20.0f, 20.0f)
                lineTo(6.0f, 20.0f)
                close()
            }
        }

    public val Sync: ImageVector =
        buildIcon("Sync") {
            strokePath {
                moveTo(21.0f, 9.0f)
                curveTo(19.5f, 5.5f, 16.0f, 3.0f, 13.0f, 3.0f)
                curveTo(8.0f, 3.0f, 4.0f, 7.0f, 4.0f, 12.0f)
            }
            strokePath {
                moveTo(5.0f, 16.0f)
                curveTo(6.5f, 19.5f, 10.0f, 22.0f, 13.0f, 22.0f)
                curveTo(18.0f, 22.0f, 22.0f, 18.0f, 22.0f, 13.0f)
            }
            strokePath {
                moveTo(1.0f, 8.0f)
                lineTo(4.0f, 12.0f)
                lineTo(8.0f, 9.0f)
            }
            strokePath {
                moveTo(25.0f, 17.0f)
                lineTo(22.0f, 13.0f)
                lineTo(18.0f, 16.0f)
            }
        }

    public val Undo: ImageVector =
        buildIcon("Undo") {
            strokePath {
                moveTo(4.0f, 10.0f)
                lineTo(16.0f, 10.0f)
                curveTo(21.0f, 10.0f, 23.0f, 13.0f, 23.0f, 16.0f)
                curveTo(23.0f, 19.0f, 21.0f, 22.0f, 17.0f, 22.0f)
            }
            strokePath {
                moveTo(9.0f, 5.0f)
                lineTo(4.0f, 10.0f)
                lineTo(9.0f, 15.0f)
            }
        }

    public val Upload: ImageVector =
        buildIcon("Upload") {
            strokePath {
                moveTo(13.0f, 17.0f)
                lineTo(13.0f, 4.0f)
            }
            strokePath {
                moveTo(7.0f, 9.0f)
                lineTo(13.0f, 3.0f)
                lineTo(19.0f, 9.0f)
            }
            strokePath {
                moveTo(4.0f, 22.0f)
                lineTo(22.0f, 22.0f)
            }
        }

    public val Volume: ImageVector =
        buildIcon("Volume") {
            strokePath {
                moveTo(3.0f, 10.0f)
                lineTo(7.0f, 10.0f)
                lineTo(12.0f, 5.0f)
                lineTo(12.0f, 21.0f)
                lineTo(7.0f, 16.0f)
                lineTo(3.0f, 16.0f)
                close()
            }
            strokePath {
                moveTo(16.0f, 9.0f)
                curveTo(18.0f, 11.0f, 18.0f, 15.0f, 16.0f, 17.0f)
            }
            strokePath {
                moveTo(19.0f, 6.0f)
                curveTo(23.0f, 10.0f, 23.0f, 16.0f, 19.0f, 20.0f)
            }
        }

    public val Warning: ImageVector =
        buildIcon("Warning") {
            strokePath {
                moveTo(13.0f, 3.0f)
                lineTo(24.0f, 22.0f)
                lineTo(2.0f, 22.0f)
                close()
            }
            strokePath {
                moveTo(13.0f, 10.0f)
                lineTo(13.0f, 16.0f)
            }
            strokePath {
                moveTo(13.0f, 18.1f)
                curveTo(13.49707f, 18.1f, 13.9f, 18.50293f, 13.9f, 19.0f)
                curveTo(13.9f, 19.49707f, 13.49707f, 19.9f, 13.0f, 19.9f)
                curveTo(12.50293f, 19.9f, 12.1f, 19.49707f, 12.1f, 19.0f)
                curveTo(12.1f, 18.50293f, 12.50293f, 18.1f, 13.0f, 18.1f)
                close()
            }
        }

    /** Every glyph, for a gallery or a test that has to know the set is complete. */
    public val All: List<Pair<String, ImageVector>> =
        listOf(
            "add" to Add,
            "attach" to Attach,
            "back" to Back,
            "calendar" to Calendar,
            "camera" to Camera,
            "cancel" to Cancel,
            "check" to Check,
            "clock" to Clock,
            "close" to Close,
            "copy" to Copy,
            "delete" to Delete,
            "download" to Download,
            "edit" to Edit,
            "favourite" to Favourite,
            "folder" to Folder,
            "info" to Info,
            "location" to Location,
            "lock" to Lock,
            "mail" to Mail,
            "menu" to Menu,
            "minus" to Minus,
            "more" to More,
            "next" to Next,
            "pause" to Pause,
            "people" to People,
            "phone" to Phone,
            "play" to Play,
            "previous" to Previous,
            "redo" to Redo,
            "refresh" to Refresh,
            "save" to Save,
            "search" to Search,
            "settings" to Settings,
            "share" to Share,
            "stop" to Stop,
            "sync" to Sync,
            "undo" to Undo,
            "upload" to Upload,
            "volume" to Volume,
            "warning" to Warning,
        )
}
