// GENERATED by scripts/generate_icons.py from the SVG files in icons/svg/.
// Draw the glyph, run `./gradlew generateKvadrantIcons`, commit both. `check` fails if this
// file and the drawings disagree.
package io.github.youndie.kvadrant.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * The application bar's glyphs, drawn for this repository.
 *
 * **Nothing here is Microsoft's.** Segoe MDL2 Assets and Segoe Fluent Icons are proprietary and
 * no open Metro-styled equivalent exists, so every one of these is drawn on the grid the
 * guidelines describe: 26 x 26 inside a 48 dp circle, a stroke of 1.5 and no fill. The circle is
 * the bar's, not the glyph's — `KvadrantAppBarButton` draws it.
 *
 * They are strokes rather than fills, so a caller tints them the way Compose tints any vector:
 * `Icon(KvadrantIcons.Back, null)` takes `LocalContentColor` through a colour filter.
 */
public object KvadrantIcons {
    public val Add: ImageVector =
        ImageVector.Builder("Add", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(13.0f, 4.0f)
                lineTo(13.0f, 22.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(4.0f, 13.0f)
                lineTo(22.0f, 13.0f)
            }
            .build()

    public val Back: ImageVector =
        ImageVector.Builder("Back", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(23.0f, 13.0f)
                lineTo(4.0f, 13.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(11.0f, 6.0f)
                lineTo(4.0f, 13.0f)
                lineTo(11.0f, 20.0f)
            }
            .build()

    public val Cancel: ImageVector =
        ImageVector.Builder("Cancel", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(5.0f, 5.0f)
                lineTo(21.0f, 21.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(21.0f, 5.0f)
                lineTo(5.0f, 21.0f)
            }
            .build()

    public val Check: ImageVector =
        ImageVector.Builder("Check", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(4.0f, 14.0f)
                lineTo(10.0f, 20.0f)
                lineTo(22.0f, 6.0f)
            }
            .build()

    public val Close: ImageVector =
        ImageVector.Builder("Close", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(13.0f, 3.0f)
                curveTo(18.5f, 3.0f, 23.0f, 7.5f, 23.0f, 13.0f)
                curveTo(23.0f, 18.5f, 18.5f, 23.0f, 13.0f, 23.0f)
                curveTo(7.5f, 23.0f, 3.0f, 18.5f, 3.0f, 13.0f)
                curveTo(3.0f, 7.5f, 7.5f, 3.0f, 13.0f, 3.0f)
                close()
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(9.0f, 9.0f)
                lineTo(17.0f, 17.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(17.0f, 9.0f)
                lineTo(9.0f, 17.0f)
            }
            .build()

    public val Delete: ImageVector =
        ImageVector.Builder("Delete", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(4.0f, 7.0f)
                lineTo(22.0f, 7.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(10.0f, 7.0f)
                lineTo(10.0f, 4.0f)
                lineTo(16.0f, 4.0f)
                lineTo(16.0f, 7.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(6.0f, 7.0f)
                lineTo(7.0f, 22.0f)
                lineTo(19.0f, 22.0f)
                lineTo(20.0f, 7.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(11.0f, 11.0f)
                lineTo(11.0f, 18.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(15.0f, 11.0f)
                lineTo(15.0f, 18.0f)
            }
            .build()

    public val Edit: ImageVector =
        ImageVector.Builder("Edit", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(4.0f, 22.0f)
                lineTo(4.0f, 17.0f)
                lineTo(17.0f, 4.0f)
                lineTo(22.0f, 9.0f)
                lineTo(9.0f, 22.0f)
                close()
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(15.0f, 6.0f)
                lineTo(20.0f, 11.0f)
            }
            .build()

    public val Refresh: ImageVector =
        ImageVector.Builder("Refresh", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(22.0f, 13.0f)
                curveTo(22.0f, 18.0f, 18.0f, 22.0f, 13.0f, 22.0f)
                curveTo(8.0f, 22.0f, 4.0f, 18.0f, 4.0f, 13.0f)
                curveTo(4.0f, 8.0f, 8.0f, 4.0f, 13.0f, 4.0f)
                curveTo(16.2f, 4.0f, 19.0f, 5.7f, 20.6f, 8.2f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(15.0f, 8.0f)
                lineTo(21.0f, 8.0f)
                lineTo(21.0f, 2.0f)
            }
            .build()

    public val Save: ImageVector =
        ImageVector.Builder("Save", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(4.0f, 4.0f)
                lineTo(18.0f, 4.0f)
                lineTo(22.0f, 8.0f)
                lineTo(22.0f, 22.0f)
                lineTo(4.0f, 22.0f)
                close()
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(8.0f, 4.0f)
                lineTo(8.0f, 11.0f)
                lineTo(17.0f, 11.0f)
                lineTo(17.0f, 4.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(8.0f, 22.0f)
                lineTo(8.0f, 15.0f)
                lineTo(18.0f, 15.0f)
                lineTo(18.0f, 22.0f)
            }
            .build()

    public val Search: ImageVector =
        ImageVector.Builder("Search", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(11.0f, 4.0f)
                curveTo(15.4f, 4.0f, 19.0f, 7.6f, 19.0f, 12.0f)
                curveTo(19.0f, 16.4f, 15.4f, 20.0f, 11.0f, 20.0f)
                curveTo(6.6f, 20.0f, 3.0f, 16.4f, 3.0f, 12.0f)
                curveTo(3.0f, 7.6f, 6.6f, 4.0f, 11.0f, 4.0f)
                close()
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(17.0f, 18.0f)
                lineTo(23.0f, 24.0f)
            }
            .build()

    public val Settings: ImageVector =
        ImageVector.Builder("Settings", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(23.86f, 11.28f)
                lineTo(23.86f, 14.72f)
                lineTo(20.78f, 14.87f)
                lineTo(19.82f, 17.18f)
                lineTo(21.9f, 19.47f)
                lineTo(19.47f, 21.9f)
                lineTo(17.18f, 19.82f)
                lineTo(14.87f, 20.78f)
                lineTo(14.72f, 23.86f)
                lineTo(11.28f, 23.86f)
                lineTo(11.13f, 20.78f)
                lineTo(8.82f, 19.82f)
                lineTo(6.53f, 21.9f)
                lineTo(4.1f, 19.47f)
                lineTo(6.18f, 17.18f)
                lineTo(5.22f, 14.87f)
                lineTo(2.14f, 14.72f)
                lineTo(2.14f, 11.28f)
                lineTo(5.22f, 11.13f)
                lineTo(6.18f, 8.82f)
                lineTo(4.1f, 6.53f)
                lineTo(6.53f, 4.1f)
                lineTo(8.82f, 6.18f)
                lineTo(11.13f, 5.22f)
                lineTo(11.28f, 2.14f)
                lineTo(14.72f, 2.14f)
                lineTo(14.87f, 5.22f)
                lineTo(17.18f, 6.18f)
                lineTo(19.47f, 4.1f)
                lineTo(21.9f, 6.53f)
                lineTo(19.82f, 8.82f)
                lineTo(20.78f, 11.13f)
                close()
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(13.0f, 9.0f)
                curveTo(15.2092f, 9.0f, 17.0f, 10.7908f, 17.0f, 13.0f)
                curveTo(17.0f, 15.2092f, 15.2092f, 17.0f, 13.0f, 17.0f)
                curveTo(10.7908f, 17.0f, 9.0f, 15.2092f, 9.0f, 13.0f)
                curveTo(9.0f, 10.7908f, 10.7908f, 9.0f, 13.0f, 9.0f)
                close()
            }
            .build()

    public val Share: ImageVector =
        ImageVector.Builder("Share", 26.0.dp, 26.0.dp, 26.0f, 26.0f)
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(4.0f, 22.0f)
                lineTo(4.0f, 10.0f)
                lineTo(22.0f, 10.0f)
                lineTo(22.0f, 22.0f)
                close()
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(13.0f, 15.0f)
                lineTo(13.0f, 3.0f)
            }
            .path(
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
            ) {
                moveTo(8.0f, 8.0f)
                lineTo(13.0f, 3.0f)
                lineTo(18.0f, 8.0f)
            }
            .build()

    /** Every glyph, for a gallery or a test that has to know the set is complete. */
    public val All: List<Pair<String, ImageVector>> =
        listOf(
            "add" to Add,
            "back" to Back,
            "cancel" to Cancel,
            "check" to Check,
            "close" to Close,
            "delete" to Delete,
            "edit" to Edit,
            "refresh" to Refresh,
            "save" to Save,
            "search" to Search,
            "settings" to Settings,
            "share" to Share,
        )
}
