// GENERATED by scripts/generate_tokens.py from the vendored metro-tokens.json.
// Edit the JSON, run `./gradlew generateKvadrantTokens`, commit both. `check` fails
// if this file and the JSON disagree.
package io.github.youndie.kvadrant.theme

import androidx.compose.ui.graphics.Color

/**
 * The specification's own numbers, as the machine-readable dump holds them.
 *
 * Each carries the dump's confidence mark, because a consumer reading a KDoc has as much
 * right to know which numbers Microsoft published as a reader of the research document does.
 * Nothing is emitted here that nothing reads.
 */
internal object KvadrantTokens {
    /** `scale.pxToDp` — every Metro pixel becomes this many dp. derived arithmetically from published numbers. */
    internal const val PX_TO_DP: Float = 0.75f

    /** The dark theme's thirteen brushes. */
    internal object Dark {
        /** `#FFFFFFFF` — verified against a Microsoft first source. */
        internal val foreground: Color = Color(0xFFFFFFFF)

        /** `#FF000000` — verified against a Microsoft first source. */
        internal val background: Color = Color(0xFF000000)

        /** `#FF000000` — verified against a Microsoft first source. */
        internal val contrastForeground: Color = Color(0xFF000000)

        /** `#FFFFFFFF` — verified against a Microsoft first source. */
        internal val contrastBackground: Color = Color(0xFFFFFFFF)

        /** `#66FFFFFF` — verified against a Microsoft first source. */
        internal val disabled: Color = Color(0x66FFFFFF)

        /** `#99FFFFFF` — verified against a Microsoft first source. */
        internal val subtle: Color = Color(0x99FFFFFF)

        /** `#FF1F1F1F` — verified against a Microsoft first source. */
        internal val chrome: Color = Color(0xFF1F1F1F)

        /** `#AA000000` — verified against a Microsoft first source. */
        internal val semitransparent: Color = Color(0xAA000000)

        /** `#BFFFFFFF` — verified against a Microsoft first source. */
        internal val border: Color = Color(0xBFFFFFFF)

        /** `#33FFFFFF` — verified against a Microsoft first source. */
        internal val inactive: Color = Color(0x33FFFFFF)

        /** `#BFFFFFFF` — verified against a Microsoft first source. */
        internal val textBox: Color = Color(0xBFFFFFFF)

        /** `#FFFFFFFF` — verified against a Microsoft first source. */
        internal val textBoxEditBackground: Color = Color(0xFFFFFFFF)

        /** `#77000000` — verified against a Microsoft first source. */
        internal val textBoxReadOnly: Color = Color(0x77000000)
    }

    /** The light theme's thirteen brushes. */
    internal object Light {
        /** `#DE000000` — verified against a Microsoft first source. */
        internal val foreground: Color = Color(0xDE000000)

        /** `#FFFFFFFF` — verified against a Microsoft first source. */
        internal val background: Color = Color(0xFFFFFFFF)

        /** `#FFFFFFFF` — verified against a Microsoft first source. */
        internal val contrastForeground: Color = Color(0xFFFFFFFF)

        /** `#DE000000` — verified against a Microsoft first source. */
        internal val contrastBackground: Color = Color(0xDE000000)

        /** `#4D000000` — verified against a Microsoft first source. */
        internal val disabled: Color = Color(0x4D000000)

        /** `#66000000` — verified against a Microsoft first source. */
        internal val subtle: Color = Color(0x66000000)

        /** `#FFDDDDDD` — verified against a Microsoft first source. */
        internal val chrome: Color = Color(0xFFDDDDDD)

        /** `#AAFFFFFF` — verified against a Microsoft first source. */
        internal val semitransparent: Color = Color(0xAAFFFFFF)

        /** `#99000000` — **corrected**: the dump repeats the dark value and flags it `unverified` with a note to re-check; the SDK's own ThemeResources gives 60 % black - research §0, correction 3. */
        internal val border: Color = Color(0x99000000)

        /** `#33000000` — verified against a Microsoft first source. */
        internal val inactive: Color = Color(0x33000000)

        /** `#26000000` — verified against a Microsoft first source. */
        internal val textBox: Color = Color(0x26000000)

        /** `#00000000` — verified against a Microsoft first source. */
        internal val textBoxEditBackground: Color = Color(0x00000000)

        /** `#2E000000` — verified against a Microsoft first source. */
        internal val textBoxReadOnly: Color = Color(0x2E000000)
    }

    /** The twenty accents, in the order the phone's settings list showed them. */
    internal object Accents {
        /** `#A4C400` — luminance 0.474, contrast 2.03 on white; derived arithmetically from published numbers. */
        internal val Lime: Color = Color(0xFFA4C400)

        /** `#60A917` — luminance 0.309, contrast 2.93 on white; derived arithmetically from published numbers. */
        internal val Green: Color = Color(0xFF60A917)

        /** `#008A00` — luminance 0.182, contrast 4.52 on white; derived arithmetically from published numbers. */
        internal val Emerald: Color = Color(0xFF008A00)

        /** `#00ABA9` — luminance 0.32, contrast 2.84 on white; derived arithmetically from published numbers. */
        internal val Teal: Color = Color(0xFF00ABA9)

        /** `#1BA1E2` — luminance 0.312, contrast 2.9 on white; verified against a Microsoft first source. */
        internal val Cyan: Color = Color(0xFF1BA1E2)

        /** `#0050EF` — luminance 0.12, contrast 5.98 on white; derived arithmetically from published numbers. */
        internal val Cobalt: Color = Color(0xFF0050EF)

        /** `#6A00FF` — luminance 0.103, contrast 6.86 on white; derived arithmetically from published numbers. */
        internal val Indigo: Color = Color(0xFF6A00FF)

        /** `#AA00FF` — luminance 0.158, contrast 5.05 on white; derived arithmetically from published numbers. */
        internal val Violet: Color = Color(0xFFAA00FF)

        /** `#F472D0` — luminance 0.358, contrast 2.57 on white; derived arithmetically from published numbers. */
        internal val Pink: Color = Color(0xFFF472D0)

        /** `#D80073` — luminance 0.158, contrast 5.04 on white; derived arithmetically from published numbers. */
        internal val Magenta: Color = Color(0xFFD80073)

        /** `#A20025` — luminance 0.078, contrast 8.2 on white; derived arithmetically from published numbers. */
        internal val Crimson: Color = Color(0xFFA20025)

        /** `#E51400` — luminance 0.172, contrast 4.73 on white; verified against a Microsoft first source. */
        internal val Red: Color = Color(0xFFE51400)

        /** `#FA6800` — luminance 0.302, contrast 2.98 on white; derived arithmetically from published numbers. */
        internal val Orange: Color = Color(0xFFFA6800)

        /** `#F0A30A` — luminance 0.447, contrast 2.11 on white; derived arithmetically from published numbers. */
        internal val Amber: Color = Color(0xFFF0A30A)

        /** `#E3C800` — luminance 0.577, contrast 12.5 on black; derived arithmetically from published numbers. */
        internal val Yellow: Color = Color(0xFFE3C800)

        /** `#825A2C` — luminance 0.122, contrast 5.91 on white; derived arithmetically from published numbers. */
        internal val Brown: Color = Color(0xFF825A2C)

        /** `#6D8764` — luminance 0.215, contrast 3.98 on white; derived arithmetically from published numbers. */
        internal val Olive: Color = Color(0xFF6D8764)

        /** `#647687` — luminance 0.174, contrast 4.68 on white; derived arithmetically from published numbers. */
        internal val Steel: Color = Color(0xFF647687)

        /** `#76608A` — luminance 0.141, contrast 5.42 on white; derived arithmetically from published numbers. */
        internal val Mauve: Color = Color(0xFF76608A)

        /** `#87794E` — luminance 0.194, contrast 4.31 on white; derived arithmetically from published numbers. */
        internal val Taupe: Color = Color(0xFF87794E)

        internal val All: List<Pair<String, Color>> =
            listOf(
                "lime" to Lime,
                "green" to Green,
                "emerald" to Emerald,
                "teal" to Teal,
                "cyan" to Cyan,
                "cobalt" to Cobalt,
                "indigo" to Indigo,
                "violet" to Violet,
                "pink" to Pink,
                "magenta" to Magenta,
                "crimson" to Crimson,
                "red" to Red,
                "orange" to Orange,
                "amber" to Amber,
                "yellow" to Yellow,
                "brown" to Brown,
                "olive" to Olive,
                "steel" to Steel,
                "mauve" to Mauve,
                "taupe" to Taupe,
            )
    }

    /**
     * The phone's type ramp, in sp: Metro pixels times [PX_TO_DP], **rounded**.
     *
     * The rounding is not a liberty. The dump stores 18.667 and 25.333, which are decimal
     * approximations of 56/3 and 76/3; three quarters of those are exactly 14 and 19, while
     * three quarters of the decimals are 14.00025 and 18.99975. Carrying the error through
     * puts every glyph a fraction of a pixel off its grid, which is visible in a golden and
     * is how it was found. The generator refuses to round anything further than a hundredth
     * of an sp, so a genuinely fractional size in the dump would stop the build rather than
     * be quietly flattened.
     */
    internal object FontSizesSp {
        /** `PhoneFontSizeSmall` 18.667 px — verified against a Microsoft first source. */
        internal const val SMALL: Float = 14f

        /** `PhoneFontSizeNormal` 20 px — verified against a Microsoft first source. */
        internal const val NORMAL: Float = 15f

        /** `PhoneFontSizeMedium` 22.667 px — verified against a Microsoft first source. */
        internal const val MEDIUM: Float = 17f

        /** `PhoneFontSizeMediumLarge` 25.333 px — verified against a Microsoft first source. */
        internal const val MEDIUM_LARGE: Float = 19f

        /** `PhoneFontSizeLarge` 32 px — verified against a Microsoft first source. */
        internal const val LARGE: Float = 24f

        /** `PhoneFontSizeExtraLarge` 42.667 px — verified against a Microsoft first source. */
        internal const val EXTRA_LARGE: Float = 32f

        /** `PhoneFontSizeExtraExtraLarge` 72 px — verified against a Microsoft first source. */
        internal const val EXTRA_EXTRA_LARGE: Float = 54f

        /** `PhoneFontSizeHuge` 186.667 px — verified against a Microsoft first source. */
        internal const val HUGE: Float = 140f
    }
}
