#!/usr/bin/env python3
"""
The on-device guard: run it, record what it said, and say how long ago that was.

    python3 scripts/android_guard.py --run       # needs a phone; records the result
    python3 scripts/android_guard.py --check     # in `make check`: the record is present and sane
    python3 scripts/android_guard.py --report    # in `make report`: how stale it is

WHY THIS EXISTS. `connectedAndroidDeviceTest` is the only thing this repository runs on Android, and
it is outside `check` on purpose — a gate that needs hardware is a gate that gets skipped (B-29). The
price was paid in full: it errored on a device, **nobody ran it for months**, and the AAR shipping
with no fonts at all (B-37) stayed invisible for exactly as long. A guard outside the gate is a guard
whose silence reads as success.

WHAT THIS CAN AND CANNOT BE. It cannot be a gate. Failing `check` when the recorded run is older than
the code would block every change to the tilt on somebody owning a phone, and a check that cannot be
satisfied honestly is one people satisfy dishonestly — by editing the record. So the mechanism
converts silence into a **number that grows**: every `make report`, in CI and locally, prints when
Android was last exercised, on what, and which of the sources that claim depends on have moved since.
Absence is invisible; a count is not.

What *is* a gate is the record's existence and shape, because that costs nothing and stops the file
being quietly deleted.

WHAT THE GATE STILL DOES NOT COVER, and this is the honest half: `CameraProbeTest` runs the same
press and the same solver on the desktop inside `check`, so the arithmetic and the geometry are held
there. What only a device can catch is hwui disagreeing with skiko — which is what B-25 was, and why
this exists at all.
"""
import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RECORD = ROOT / "docs" / "android-device-runs.md"

# What the on-device claim depends on. **A wrong list here makes the report lie in the reassuring
# direction**, so it is deliberately wider than the strict dependency: the whole indication package
# rather than the two files the solver reads, because a change to the press or the unwind moves the
# trapezoid the probe measures just as surely as a change to the camera does.
WATCHED = (
    "kvadrant-core/src/commonMain/kotlin/io/github/youndie/kvadrant/indication",
    "kvadrant-core/src/commonMain/kotlin/io/github/youndie/kvadrant/foundation/KvadrantCamera.kt",
    "kvadrant-core/src/commonMain/kotlin/io/github/youndie/kvadrant/theme/KvadrantMetrics.kt",
    "kvadrant-core/src/androidDeviceTest",
    "kvadrant-core/build.gradle.kts",
    "gradle/libs.versions.toml",
)

HEADER = """# Android device runs

Generated by `scripts/android_guard.py --run`. **Newest first, and nothing here is written by hand**
— a row is added by a run that passed, so a row is evidence rather than an intention.

Why this file exists at all is in the script's own docstring, and the short version is that
`connectedAndroidDeviceTest` is outside `check` for a reason and was therefore invisible for months.

| When (UTC) | Device | Android | Camera probe | Commit |
|---|---|---|---|---|
"""


def rows():
    if not RECORD.exists():
        return []
    out = []
    for line in RECORD.read_text().splitlines():
        if not line.startswith("| 20"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) == 5:
            out.append(
                {
                    "when": cells[0],
                    "device": cells[1],
                    "api": cells[2],
                    "camera": cells[3],
                    "commit": cells[4],
                }
            )
    return out


def git(*args):
    return subprocess.run(
        ("git",) + args, cwd=ROOT, capture_output=True, text=True, check=False
    ).stdout.strip()


def adb(*args):
    binary = Path.home() / "Library" / "Android" / "sdk" / "platform-tools" / "adb"
    executable = str(binary) if binary.exists() else "adb"
    return subprocess.run(
        (executable,) + args, capture_output=True, text=True, check=False
    ).stdout.strip()


def run():
    device = adb("shell", "getprop", "ro.product.model") or "unknown"
    api = adb("shell", "getprop", "ro.build.version.sdk") or "unknown"
    if device == "unknown":
        sys.exit("no device: `adb devices` shows nothing, and this records only runs that happened")
    print(f"running the on-device guard on {device}, API {api}")
    # Cleared first, so what is read back belongs to this run and not to the last one.
    adb("logcat", "-c")
    result = subprocess.run(
        ("./gradlew", ":kvadrant-core:connectedAndroidDeviceTest"), cwd=ROOT, check=False
    )
    if result.returncode != 0:
        # **Nothing is recorded for a failed run**, and that is the point of recording at all: the
        # file says what has been shown to work, so a row cannot be produced by a run that did not.
        sys.exit("the on-device guard failed; nothing recorded")
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
    commit = git("rev-parse", "HEAD")[:12]
    camera = probe_reading() or "not reported"
    existing = RECORD.read_text() if RECORD.exists() else HEADER
    if "| When (UTC) |" not in existing:
        existing = HEADER
    head, _, tail = existing.partition("|---|---|---|---|---|\n")
    RECORD.write_text(
        f"{head}|---|---|---|---|---|\n"
        f"| {stamp} | {device} | {api} | {camera} | `{commit}` |\n{tail}"
    )
    print(f"recorded: {stamp}, {device}, API {api}, {camera}, {commit}")


def probe_reading():
    """
    The number B-29 said Android would get instead of goldens.

    It was computed and thrown away for as long as this guard has existed: the test solved the
    camera's depth, compared it against a six per cent window and discarded it, so two runs a year
    apart on two Android versions were indistinguishable as long as both passed. The test now logs
    it and this reads it back, because a tolerance says whether a run was acceptable and a number
    says what changed.
    """
    for line in reversed(adb("logcat", "-d", "-s", "KvadrantProbe:I").splitlines()):
        marker = "camera solved="
        if marker in line:
            return line[line.index(marker) + len("camera ") :].strip()
    return None


def check():
    found = rows()
    if not found:
        sys.exit(
            f"{RECORD.relative_to(ROOT)} holds no runs. It is the only evidence that anything in "
            f"this repository has ever executed on Android; a run adds a row to it."
        )
    print(f"{len(found)} recorded Android device runs, newest {found[0]['when']}")


def report():
    found = rows()
    if not found:
        print("Android: never recorded as run. See scripts/android_guard.py.")
        return
    latest = found[0]
    commit = latest["commit"].strip("`")
    print(
        f"Android: last exercised {latest['when']} UTC on {latest['device']}, "
        f"API {latest['api']}, at {commit} — {latest['camera']}"
    )
    if not git("cat-file", "-t", commit):
        print("  that commit is not in this checkout, so nothing can be said about what moved since")
        return
    behind = git("rev-list", "--count", f"{commit}..HEAD")
    moved = git("diff", "--name-only", f"{commit}..HEAD", "--", *WATCHED).splitlines()
    print(f"  {behind or '0'} commits ago")
    if moved:
        # The actionable half. A count on its own is a number people stop reading; a list of the
        # files whose behaviour the recorded number was measured against is a reason to plug a phone
        # in.
        print(f"  {len(moved)} of the sources that claim depends on have changed since:")
        for path in moved:
            print(f"    {path}")
    else:
        print("  nothing the claim depends on has changed since")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report", action="store_true")
    args = parser.parse_args()
    if args.run:
        run()
    elif args.check:
        check()
    elif args.report:
        report()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
