#!/usr/bin/env python3
"""
The component catalogue: what this library exposes, and which of it a reader can press.

    python3 scripts/component_catalog.py            # rewrite the generated table in docs/components.md
    python3 scripts/component_catalog.py --check    # fail if that table is out of date

WHY THIS IS GENERATED. A hand-written catalogue of forty components is wrong within a fortnight and
wrong in the direction that costs most: it keeps listing what was removed and stops listing what was
added, and both failures look exactly like a correct document. So the table is derived from the two
things that cannot lie about it — the sources of `kvadrant-core`, and the preview registry as the
compiler built it.

WHAT IT CHECKS, AND IN BOTH DIRECTIONS.

  * A public composable that is not in the table is an error. That is the rot this exists to stop.
  * A preview naming a composable that does not exist is an error. It means the site has a page for
    something that was renamed or deleted, and a page for a component nobody can call is worse than
    no page: it reads as documentation.

WHAT IT DOES NOT CHECK. That every composable *has* a preview. Some legitimately cannot have one on
their own -- `KvadrantTheme` is a wrapper with no appearance -- and a rule with exemptions in it is
a rule that gets an exemption added rather than a preview written. The uncovered ones are listed in
the table with an empty preview column and counted in the line under it, so the gap is a number in
the document rather than a silence.

THE PREVIEW INDEX comes from `./gradlew :kvadrant-previews:previewIndex`, which runs the registry.
Without it -- `make check` on its own does not build anything -- the preview column is carried over
from the table as it stands and every other column is still verified. That is a smaller claim than
the one made with the index present, and the script says which of the two it made rather than
leaving the reader to guess. Emitting an empty column instead would read as "nothing has a preview",
which is a false document rather than an unverified one.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "kvadrant-core/src/commonMain/kotlin/io/github/youndie/kvadrant"
CATALOG = ROOT / "docs/components.md"
PREVIEW_INDEX = ROOT / "kvadrant-previews/build/preview-index.json"

BEGIN = "<!-- BEGIN CATALOG - generated by scripts/component_catalog.py, do not edit by hand -->"
END = "<!-- END CATALOG -->"

DECLARATION = re.compile(
    r"^public\s+(?:inline\s+)?fun\s*(?:<[^>]*>\s*)?(?:(?P<receiver>[A-Za-z_][\w.]*)\.)?"
    r"(?P<name>[A-Za-z_]\w*)\s*\("
)


def kdoc_summary(lines, index):
    """
    The first sentence of the KDoc above the declaration at `index`, or an empty string.

    The first sentence rather than the first line: these KDocs open with a sentence that wraps, and
    a first line alone reads as a truncation. Everything after it is the transcription argument,
    which belongs on the component's own page and not in an index.
    """
    cursor = index - 1
    while cursor >= 0 and lines[cursor].lstrip().startswith("@"):
        cursor -= 1
    # A one-line KDoc — `/** ... */` — ends on the same line it starts, so a scan that only looks
    # for a closing `*/` on its own line misses it. Three components were reported as having no
    # documentation for exactly that reason, which is the shape of mistake this whole file exists
    # to stop somebody making by hand.
    if cursor < 0 or not lines[cursor].strip().endswith("*/"):
        return ""
    end = cursor
    start = end
    while start >= 0 and not lines[start].lstrip().startswith("/**"):
        start -= 1
    if start < 0:
        return ""
    body = []
    for line in lines[start:end + 1]:
        text = line.strip()
        text = re.sub(r"^/\*\*", "", text)
        text = re.sub(r"\*/$", "", text)
        text = re.sub(r"^\*\s?", "", text)
        body.append(text.strip())
    prose = " ".join(part for part in body if part).strip()
    # `[KvadrantText]` and `**bold**` are KDoc markup; the table is markdown and reads them
    # differently, so the brackets go and the emphasis stays.
    prose = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", prose)
    prose = re.sub(r"\[([^\]]+)\]", r"`\1`", prose)
    # On a full stop only. Splitting on a colon as well cut "Two lines: a title and a subtitle"
    # down to "Two lines", which is not a summary of anything.
    sentence = re.split(r"(?<=\.)\s", prose, maxsplit=1)[0]
    return sentence.strip().rstrip(".")


def composables():
    """Every public composable in the core, in file then declaration order."""
    found = []
    for path in sorted(CORE.rglob("*.kt")):
        lines = path.read_text().splitlines()
        for index, line in enumerate(lines):
            match = DECLARATION.match(line)
            if not match:
                continue
            annotations = []
            cursor = index - 1
            while cursor >= 0 and lines[cursor].lstrip().startswith("@"):
                annotations.append(lines[cursor].strip())
                cursor -= 1
            if not any("@Composable" in a for a in annotations):
                continue
            name = match.group("name")
            receiver = match.group("receiver")
            found.append(
                {
                    "name": name,
                    "receiver": receiver,
                    "path": str(path.relative_to(ROOT)),
                    "summary": kdoc_summary(lines, index),
                }
            )
    # Overloads are one entry. `kvadrantCyrillic` has two, and listing both puts the same name in
    # the table twice with different prose beside it, which reads as two components.
    seen = set()
    unique = []
    for item in found:
        if item["name"] in seen:
            continue
        seen.add(item["name"])
        unique.append(item)
    return unique


def previews():
    """The registry, or None when it has not been dumped in this working tree."""
    if not PREVIEW_INDEX.exists():
        return None
    return json.loads(PREVIEW_INDEX.read_text())


def build_table(items, index, carried, carried_summary):
    by_component = {}
    for preview in index or []:
        by_component.setdefault(preview["component"], []).append(preview["id"])

    rows = [
        "| Component | Preview | Source | What it is |",
        "|---|---|---|---|",
    ]
    uncovered = 0
    for item in items:
        ids = by_component.get(item["name"], [])
        if index is None:
            preview_cell = carried.get(item["name"], "—")
        elif ids:
            preview_cell = " ".join(f"`{i}`" for i in ids)
        else:
            preview_cell = "—"
            uncovered += 1
        source = f"[{Path(item['path']).name}]({relative_link(item['path'])})"
        rows.append(f"| `{item['name']}` | {preview_cell} | {source} | {item['summary']} |")

    rows.append("")
    # The count line is regenerated only when the registry was actually read. Rewriting it from a
    # carried-over column would state a verified fact on unverified data, and it is the one line in
    # the table a reader takes at face value.
    rows.append(
        carried_summary
        if index is None
        else (
            f"{len(items)} public composables, {len(index)} previews, "
            f"{uncovered} composables with no preview of their own."
        )
    )
    return "\n".join(rows)


def relative_link(path):
    """`docs/components.md` is one directory down, so every path into the code climbs out of it."""
    return "../" + path


def carried_summary_line(document):
    """The count line under the table, so a run without the registry does not rewrite it."""
    body = document.split(BEGIN, 1)[1].split(END, 1)[0]
    tail = [line.strip() for line in body.splitlines() if line.strip() and not line.startswith("|")]
    return tail[-1] if tail else ""


def carried_preview_column(document):
    """
    The preview cells of the table as it currently stands, keyed by component.

    Read back so that a run without the registry can leave that column exactly as it was instead of
    blanking it. It parses the generated table, which is a thing this script wrote itself — the one
    case where reading one's own output is not a second source of truth.
    """
    cells = {}
    for line in document.splitlines():
        match = re.match(r"\|\s*`([A-Za-z_]\w*)`\s*\|([^|]*)\|", line)
        if match:
            cells[match.group(1)] = match.group(2).strip()
    return cells


def orphan_previews(items, index):
    known = {item["name"] for item in items}
    # Three previews are about things that are not composables: `KvadrantAccents` is a palette,
    # `KvadrantIcons` a set of drawings, `KvadrantTypography` a ramp. Each of them has an appearance
    # and each is what a reader looks at first, so each gets a preview. They are checked against the
    # sources here rather than exempted from the check — a renamed object still fails this.
    sources = " ".join(p.read_text() for p in CORE.rglob("*.kt"))
    return sorted(
        {
            preview["component"]
            for preview in index or []
            if preview["component"] not in known
            and not re.search(
                r"\bpublic (?:object|data class|class|fun) (?:Modifier\.)?"
                + re.escape(preview["component"])
                + r"\b",
                sources,
            )
        }
    )


# The README states the count in words, and it was wrong by three the day this was added — the
# catalogue below it is generated and checked, and the sentence a reader meets first was not. A
# number that lives in two places drifts in the one nobody generates.
NUMERALS = {
    40: "forty", 41: "forty-one", 42: "forty-two", 43: "forty-three", 44: "forty-four",
    45: "forty-five", 46: "forty-six", 47: "forty-seven", 48: "forty-eight", 49: "forty-nine",
    50: "fifty", 51: "fifty-one", 52: "fifty-two", 53: "fifty-three", 54: "fifty-four",
    55: "fifty-five", 56: "fifty-six", 57: "fifty-seven", 58: "fifty-eight", 59: "fifty-nine",
    60: "sixty", 61: "sixty-one", 62: "sixty-two", 63: "sixty-three", 64: "sixty-four",
    65: "sixty-five", 66: "sixty-six", 67: "sixty-seven", 68: "sixty-eight", 69: "sixty-nine",
    70: "seventy",
}
COUNT_SENTENCE = re.compile(r"([A-Za-z-]+) public composables")


def readme_count(total):
    """The README's spelled-out count, against the one just scanned. A message, or None."""
    readme = ROOT / "README.md"
    text = readme.read_text()
    found = COUNT_SENTENCE.search(text)
    if not found:
        return (
            "README.md no longer says how many public composables there are, so this check "
            "verified nothing. Restore the sentence or delete this check deliberately"
        )
    expected = NUMERALS.get(total)
    if expected is None:
        return (
            f"{total} composables, and this check cannot spell it. Extend NUMERALS in "
            "scripts/component_catalog.py"
        )
    written = found.group(1).lower()
    if written != expected:
        return (
            f"README.md says {written} public composables and the scan finds {total} "
            f"({expected}). The catalogue is generated; that sentence is not"
        )
    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    items = composables()
    if not items:
        sys.exit("no public composables found in %s — the scan is broken, not the library" % CORE)
    index = previews()

    problems = orphan_previews(items, index)
    if problems:
        sys.exit(
            "previews name components that do not exist in kvadrant-core: %s" % ", ".join(problems)
        )

    document = CATALOG.read_text()
    table = build_table(
        items, index, carried_preview_column(document), carried_summary_line(document)
    )
    if BEGIN not in document or END not in document:
        sys.exit(f"{CATALOG} has no {BEGIN} / {END} markers")
    head, rest = document.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = f"{head}{BEGIN}\n\n{table}\n\n{END}{tail}"

    if arguments.check:
        if updated != document:
            sys.exit(
                f"{CATALOG.relative_to(ROOT)} is out of date. Run: python3 scripts/component_catalog.py"
            )
        readme_problem = readme_count(len(items))
        if readme_problem:
            sys.exit(readme_problem)
        verified = "sources and previews" if index else "sources only (no preview index built)"
        print(f"catalogue is current: {len(items)} composables, verified against {verified}")
        return

    CATALOG.write_text(updated)
    print(f"{CATALOG.relative_to(ROOT)}: {len(items)} composables")


if __name__ == "__main__":
    main()
