#!/usr/bin/env python3
"""Turn the SVG glyphs in `icons/svg/` into Kotlin `ImageVector`s.

B-18. Nothing can be copied: Segoe MDL2 Assets and Segoe Fluent Icons are proprietary and there is
no open Metro-styled equivalent, so every glyph here is drawn for this repository. Drawing them is a
designer's job and transcribing path data by hand is nobody's, which is what this is for.

    python3 scripts/generate_icons.py            # write the Kotlin
    python3 scripts/generate_icons.py --check    # fail if the committed output is stale

**The SVG subset is deliberately small: `M`, `L`, `C` and `Z`, absolute only.** Anything else stops
the generator with the glyph and the command named. A parser that guesses at arcs and relative
commands is a parser that silently draws the wrong shape, and a wrong shape in an icon set is the
kind of defect that survives review — it looks like a decision.
"""
import argparse
import os
import re
import sys

SOURCE = "icons/svg"
TARGET = "kvadrant-core/src/commonMain/kotlin/io/github/youndie/kvadrant/icons/KvadrantIcons.kt"

# The grid every glyph is drawn on: 26 x 26 inside a 48 dp circle, stroke 1.5, no fill.
GRID = 26.0
STROKE = 1.5

ALLOWED = set("MLCZmlcz")


def commands(d: str, name: str):
    """`d` as a list of (letter, [numbers]), refusing anything outside the subset."""
    parts = re.findall(r"([A-Za-z])([^A-Za-z]*)", d)
    out = []
    for letter, rest in parts:
        if letter not in ALLOWED:
            sys.exit(f"{name}: command '{letter}' is outside the M/L/C/Z subset this parser accepts")
        if letter.islower() and letter != "z":
            sys.exit(f"{name}: relative command '{letter}'; draw it in absolute coordinates")
        numbers = [float(n) for n in re.findall(r"-?\d*\.?\d+", rest)]
        out.append((letter.upper(), numbers))
    return out


def kotlin_path(d: str, name: str) -> list[str]:
    lines = []
    for letter, n in commands(d, name):
        if letter == "M":
            lines.append(f"                moveTo({n[0]}f, {n[1]}f)")
        elif letter == "L":
            for i in range(0, len(n), 2):
                lines.append(f"                lineTo({n[i]}f, {n[i + 1]}f)")
        elif letter == "C":
            for i in range(0, len(n), 6):
                args = ", ".join(f"{v}f" for v in n[i:i + 6])
                lines.append(f"                curveTo({args})")
        elif letter == "Z":
            lines.append("                close()")
    return lines


def title(stem: str) -> str:
    return "".join(part.capitalize() for part in stem.split("_"))


def render(names: list[str]) -> str:
    out = [
        "// GENERATED by scripts/generate_icons.py from the SVG files in icons/svg/.",
        "// Draw the glyph, run `./gradlew generateKvadrantIcons`, commit both. `check` fails if this",
        "// file and the drawings disagree.",
        "package io.github.youndie.kvadrant.icons",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.graphics.SolidColor",
        "import androidx.compose.ui.graphics.StrokeCap",
        "import androidx.compose.ui.graphics.StrokeJoin",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import androidx.compose.ui.graphics.vector.path",
        "import androidx.compose.ui.unit.dp",
        "",
        "/**",
        " * The application bar's glyphs, drawn for this repository.",
        " *",
        " * **Nothing here is Microsoft's.** Segoe MDL2 Assets and Segoe Fluent Icons are proprietary and",
        " * no open Metro-styled equivalent exists, so every one of these is drawn on the grid the",
        " * guidelines describe: 26 x 26 inside a 48 dp circle, a stroke of 1.5 and no fill. The circle is",
        " * the bar's, not the glyph's — `KvadrantAppBarButton` draws it.",
        " *",
        " * They are strokes rather than fills, so a caller tints them the way Compose tints any vector:",
        " * `Icon(KvadrantIcons.Back, null)` takes `LocalContentColor` through a colour filter.",
        " */",
        "public object KvadrantIcons {",
    ]
    first = True
    for stem in names:
        with open(os.path.join(SOURCE, stem + ".svg"), encoding="utf-8") as handle:
            svg = handle.read()
        paths = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
        if not paths:
            sys.exit(f"{stem}: no <path d=...> found; this generator reads paths and nothing else")
        if not first:
            out.append("")
        first = False
        out.append(f"    public val {title(stem)}: ImageVector =")
        out.append(f'        ImageVector.Builder("{title(stem)}", {GRID}.dp, {GRID}.dp, {GRID}f, {GRID}f)')
        for d in paths:
            out.append("            .path(")
            out.append("                stroke = SolidColor(Color.Black),")
            out.append(f"                strokeLineWidth = {STROKE}f,")
            out.append("                strokeLineCap = StrokeCap.Butt,")
            out.append("                strokeLineJoin = StrokeJoin.Miter,")
            out.append("            ) {")
            out.extend(kotlin_path(d, stem))
            out.append("            }")
        out.append("            .build()")
    out.append("")
    out.append("    /** Every glyph, for a gallery or a test that has to know the set is complete. */")
    out.append("    public val All: List<Pair<String, ImageVector>> =")
    out.append("        listOf(")
    for stem in names:
        out.append(f'            "{stem}" to {title(stem)},')
    out.append("        )")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not os.path.isdir(SOURCE):
        sys.exit(f"{SOURCE} is not there; run from the repository root")
    names = sorted(f[:-4] for f in os.listdir(SOURCE) if f.endswith(".svg"))
    if not names:
        sys.exit(f"{SOURCE} holds no SVG files")
    generated = render(names)
    if args.check:
        current = open(TARGET, encoding="utf-8").read() if os.path.exists(TARGET) else ""
        if current != generated:
            print(f"{TARGET} does not match the drawings in {SOURCE}.")
            print("Run `./gradlew generateKvadrantIcons` and commit the result.")
            return 1
        print(f"{TARGET} matches {SOURCE} ({len(names)} glyphs).")
        return 0
    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(generated)
    print(f"wrote {TARGET} ({len(names)} glyphs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
