#!/usr/bin/env python3
"""Generate the Kotlin token constants from `metro-tokens.json`.

B-06. The specification is several hundred numbers, and typing them is several hundred chances to
be wrong in a way no test catches - because the test would be typed from the same source by the
same person on the same afternoon. Generating them makes the JSON the source and any test a
comparison against it rather than a restatement of it.

Only what something reads is generated. A token emitted before anything uses it is a number nobody
has checked, which is the same failure with more lines.

    python3 scripts/generate_tokens.py            # write the file
    python3 scripts/generate_tokens.py --check    # fail if the committed file differs
"""
import argparse
import json
import os
import sys

SOURCE = "reference/metro-compose-brief/references/metro-tokens.json"
TARGET = "kvadrant-core/src/commonMain/kotlin/io/github/youndie/kvadrant/theme/KvadrantTokens.kt"

# How the JSON marks a number's provenance, in the words the research document uses. Anything not
# on this list is a mark the dump has grown since and a person should look at it.
# The dump documents exactly three, in its own `notes`: "confidence: verified | derived |
# unverified". Anything else means the dump has grown a mark since, and a person should look at it
# rather than have it silently rendered as prose nobody chose.
CONFIDENCE = {
    "verified": "verified against a Microsoft first source",
    "derived": "derived arithmetically from published numbers",
    "unverified": "**no public source states this** - see research §1.10",
}

# Where the dump is wrong and the research document says so.
#
# The brief is vendored evidence and evidence does not get amended, so a correction lives here, with
# the value the dump holds recorded beside it: if the dump is ever fixed, `--check` says so instead
# of letting a stale override sit on top of a corrected source. Each entry costs a line in
# research §0's list of corrections, which is the point of making it awkward.
CORRECTIONS = {
    ("light", "border"): (
        "#BFFFFFFF",
        "#99000000",
        "the dump repeats the dark value and flags it `unverified` with a note to re-check; the "
        "SDK's own ThemeResources gives 60 % black - research §0, correction 3",
    ),
}

TITLE = {
    "lime": "Lime", "green": "Green", "emerald": "Emerald", "teal": "Teal", "cyan": "Cyan",
    "cobalt": "Cobalt", "indigo": "Indigo", "violet": "Violet", "pink": "Pink",
    "magenta": "Magenta", "crimson": "Crimson", "red": "Red", "orange": "Orange",
    "amber": "Amber", "yellow": "Yellow", "brown": "Brown", "olive": "Olive", "steel": "Steel",
    "mauve": "Mauve", "taupe": "Taupe",
}


def screaming(name: str) -> str:
    """`mediumLarge` becomes `MEDIUM_LARGE`, which is what ktlint asks of a `const val`."""
    return "".join("_" + c if c.isupper() else c.upper() for c in name)


def mark(confidence: str) -> str:
    if confidence not in CONFIDENCE:
        sys.exit(f"unknown confidence mark {confidence!r} in {SOURCE}; add it to CONFIDENCE")
    return CONFIDENCE[confidence]


def argb(hex_or_argb: str) -> str:
    value = hex_or_argb.lstrip("#")
    if len(value) == 6:
        value = "FF" + value
    return "0x" + value.upper()


def render(data: dict) -> str:
    scale = data["scale"]["pxToDp"]
    out = []
    out.append("// GENERATED by scripts/generate_tokens.py from the vendored metro-tokens.json.")
    out.append("// Edit the JSON, run `./gradlew generateKvadrantTokens`, commit both. `check` fails")
    out.append("// if this file and the JSON disagree.")
    out.append("package io.github.youndie.kvadrant.theme")
    out.append("")
    out.append("import androidx.compose.ui.graphics.Color")
    out.append("")
    out.append("/**")
    out.append(" * The specification's own numbers, as the machine-readable dump holds them.")
    out.append(" *")
    out.append(" * Each carries the dump's confidence mark, because a consumer reading a KDoc has as much")
    out.append(" * right to know which numbers Microsoft published as a reader of the research document does.")
    out.append(" * Nothing is emitted here that nothing reads.")
    out.append(" */")
    out.append("internal object KvadrantTokens {")
    out.append(f"    /** `scale.pxToDp` — every Metro pixel becomes this many dp. {mark('derived')}. */")
    out.append(f"    internal const val PX_TO_DP: Float = {scale}f")
    out.append("")

    for theme in ("dark", "light"):
        out.append(f"    /** The {theme} theme's thirteen brushes. */")
        out.append(f"    internal object {theme.capitalize()} {{")
        for index, (name, entry) in enumerate(data["color"][theme].items()):
            if index:
                out.append("")
            correction = CORRECTIONS.get((theme, name))
            if correction is None:
                out.append(f"        /** `{entry['argb']}` — {mark(entry['confidence'])}. */")
                out.append(f"        internal val {name}: Color = Color({argb(entry['argb'])})")
                continue
            expected, corrected, reason = correction
            if entry["argb"] != expected:
                sys.exit(
                    f"the dump's {theme}.{name} is {entry['argb']}, not the {expected} this "
                    f"correction was written against. Re-read it and either drop the correction "
                    f"from CORRECTIONS or update it."
                )
            out.append(f"        /** `{corrected}` — **corrected**: {reason}. */")
            out.append(f"        internal val {name}: Color = Color({argb(corrected)})")
        out.append("    }")
        out.append("")

    out.append("    /** The twenty accents, in the order the phone's settings list showed them. */")
    out.append("    internal object Accents {")
    for index, item in enumerate(data["accents"]["items"]):
        name = TITLE.get(item["name"])
        if name is None:
            sys.exit(f"accent {item['name']!r} has no Kotlin name; add it to TITLE")
        if index:
            out.append("")
        out.append(
            f"        /** `{item['hex']}` — luminance {item['luminance']}, contrast {item['contrast']}"
            f" on {item['onColor']}; {mark(item['confidence'])}. */"
        )
        out.append(f"        internal val {name}: Color = Color({argb(item['hex'])})")
    out.append("")
    out.append("        internal val All: List<Pair<String, Color>> =")
    out.append("            listOf(")
    for item in data["accents"]["items"]:
        out.append(f'                "{item["name"]}" to {TITLE[item["name"]]},')
    out.append("            )")
    out.append("    }")
    out.append("")

    sizes = data["typography"]["windowsPhone"]["sizesPx"]
    out.append("    /**")
    out.append("     * The phone's type ramp, in sp: Metro pixels times [PX_TO_DP], **rounded**.")
    out.append("     *")
    out.append("     * The rounding is not a liberty. The dump stores 18.667 and 25.333, which are decimal")
    out.append("     * approximations of 56/3 and 76/3; three quarters of those are exactly 14 and 19, while")
    out.append("     * three quarters of the decimals are 14.00025 and 18.99975. Carrying the error through")
    out.append("     * puts every glyph a fraction of a pixel off its grid, which is visible in a golden and")
    out.append("     * is how it was found. The generator refuses to round anything further than a hundredth")
    out.append("     * of an sp, so a genuinely fractional size in the dump would stop the build rather than")
    out.append("     * be quietly flattened.")
    out.append("     */")
    out.append("    internal object FontSizesSp {")
    for index, (name, px) in enumerate(sizes.items()):
        exact = px * scale
        rounded = round(exact)
        if abs(exact - rounded) > 0.01:
            sys.exit(
                f"typography.sizesPx.{name} is {px} px, which is {exact} sp and not within a "
                f"hundredth of a whole number. Decide what it should be rather than rounding it here."
            )
        if index:
            out.append("")
        out.append(
            f"        /** `PhoneFontSize{name[0].upper()}{name[1:]}` {px} px — {mark('verified')}. */"
        )
        out.append(f"        internal const val {screaming(name)}: Float = {rounded}f")
    out.append("    }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not os.path.exists(SOURCE):
        sys.exit(f"{SOURCE} is not there; run from the repository root")
    generated = render(json.load(open(SOURCE, encoding="utf-8")))

    if args.check:
        current = open(TARGET, encoding="utf-8").read() if os.path.exists(TARGET) else ""
        if current != generated:
            print(f"{TARGET} does not match the JSON it is generated from.")
            print("Run `./gradlew generateKvadrantTokens` and commit the result.")
            return 1
        print(f"{TARGET} matches {SOURCE}.")
        return 0

    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(generated)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
